### ISSUE TITLE
Crash when subscribing to an invalid topic

### ISSUE THREAD

**Issue by hiteshchopra11** [gojek/courier-android#32]
There is a crash when we try to connect to an invalid topic. 
For example **home#** or **home+**

Steps to reproduce -:

1. Connect to a MQTT broker
2. Subscribe to an invalid topic name. Example `home#`

Error Logs -:

```
2022-07-16 13:45:37.778 10608-10647/com.gojek.courier.app E/AndroidRuntime: FATAL EXCEPTION: MQTT_Thread
    Process: com.gojek.courier.app, PID: 10608
    java.lang.IllegalArgumentException: Invalid usage of multi-level wildcard in topic string: home#
        at org.eclipse.paho.client.mqttv3.MqttTopic.validate(MqttTopic.java:200)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:889)
        at com.gojek.mqtt.connection.MqttConnection.subscribe(MqttConnection.kt:474)
        at com.gojek.mqtt.client.v3.impl.AndroidMqttClient.subscribeMqtt(AndroidMqttClient.kt:465)
        at com.gojek.mqtt.scheduler.runnable.SubscribeRunnable.run(SubscribeRunnable.kt:11)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

[Video for your reference](https://drive.google.com/file/d/1_CPONzLarm94XSaaRp78O-GmxpL95eMX/view?usp=sharing)

**Comment by hiteshchopra11** [comment]
Catching the exception in MqttConnection subscribe method seems to fix it

https://github.com/gojek/courier-android/pull/33
